# Generated by Django 5.2.1 on 2026-02-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveticker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTickerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='liveticker_app.liveticker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
