# Generated by Django 5.2.1 on 2026-02-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveticker_app', '0002_livetickerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetickerevent',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livetickerevent',
            name='link_label',
            field=models.CharField(blank=True, help_text='z. B. Mehr erfahren', max_length=100),
        ),
        migrations.AddField(
            model_name='livetickerevent',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
